export { default as articleRoutes } from './article-routes.js'
export { default as tagRoutes } from './tag-routes.js'
export { default as chatRoutes } from './chat-routes.js'
export { default as briefRoutes } from './brief-routes.js'
export { default as activityRoutes } from './activity-routes.js'
